# Generated by Django 5.0.2 on 2024-04-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_patientfeedback_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.CreateModel(
            name='Daily_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_the_day', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('no dosage', 'no dosage')], default='no', max_length=10)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.patients')),
            ],
        ),
    ]
