# Generated by Django 5.0.2 on 2024-04-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_patientfeedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
