# Generated by Django 5.0.2 on 2024-04-29 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_patients_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyclerk',
            name='admin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_clerk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmacyclerk',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
