# Generated by Django 5.0.2 on 2024-04-29 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_customuser_user_type_alter_doctor_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
