# Generated by Django 5.0.2 on 2024-04-29 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_alter_patients_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patients',
            name='admin',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
