# Generated by Django 5.0.2 on 2024-04-29 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_patients_user_alter_patients_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
        migrations.AlterField(
            model_name='patients',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
